### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Xapon260486** [DEgITx/rats-search#1]
[rats.log](https://github.com/DEgITx/rats-search/files/1678492/rats.log)

**Comment by DEgITx** [comment]
попробуй скачать текущую версию, может быть помогло

**Comment by Xapon260486** [comment]
Nope, nothing changed

**Comment by DEgITx** [comment]
https://www.dropbox.com/s/x8j66o4awfytb7m/Rats%20on%20The%20Boat%20Setup%200.1.0.exe?dl=1 - попробуй эту сборку, она может криво работать, но зато есть вероятность что запуститься

**Comment by Xapon260486** [comment]
Ииии снова нет

**Comment by DEgITx** [comment]
скинь сейчас лог rats.log после этой

**Comment by Xapon260486** [comment]
[rats.log](https://github.com/DEgITx/rats-search/files/1678714/rats.log)
А толку, там ничего не поменялось

**Comment by DEgITx** [comment]
кстати sphinx.conf есть в папке рядом с логом?

**Comment by Xapon260486** [comment]
Nope, я помню, я бы отправил

**Comment by Xapon260486** [comment]
Тьфу, что я несу, конфиг есть -_\\

**Comment by DEgITx** [comment]
оно вылетает как раз когда все остальное должно появиться, притом т.к. я такого у себя не могу воспроизвести, приходиться тебя мучать )

короче попробуй открыть cmd через выполнить, введи следующие команды:
cd /D "c:\Users\maksi\AppData\Local\Programs\rats-search\"
searchd --config "c:\Users\maksi\AppData\Roaming\Rats on The Boat\sphinx.conf"

если вдруг появиться searchd.log скинь, по хорошему оно запуститься и не отпустит консоль, по плохому сразу выйдет

**Comment by Xapon260486** [comment]
В моем случае видимо все ОЧЕНЬ плохо. Первую команду консоль приняла, вторую, в общем то, тоже, но тут полезли окошки
![screenshot_1](https://user-images.githubusercontent.com/35968146/35582801-552ba4b4-0609-11e8-8975-fcfb123630bc.png)
![screenshot_2](https://user-images.githubusercontent.com/35968146/35582809-5a3215ba-0609-11e8-86a6-61253553f5cc.png)
Лога не появилось
Лог Rats не изменился

**Comment by DEgITx** [comment]
ну вот уже что-то проясняется

**Comment by DEgITx** [comment]
перекачай сборку с гитхаба, вроде добавил недостающее

**Comment by Xapon260486** [comment]
Все, запустилось
Поиск начнется автоматически или это где то еще запустить надо?
[rats.log](https://github.com/DEgITx/rats-search/files/1678853/rats.log)
[searchd.log](https://github.com/DEgITx/rats-search/files/1678854/searchd.log)
На всякий случай закину логи, мало ли

**Comment by DEgITx** [comment]
если порты открыты которые я указывал в посте (это вдруг если роутер есть, то бывает там надо открывать), то автоматически понемногу начнет собирать

**Comment by Xapon260486** [comment]
Аррр, мне проще роутер отключить, чем открыть его порты , это просто нереально, он игнорирует все правила , прописанные в нем .-.

**Comment by Xapon260486** [comment]
А как вообще определить, что он ищет?Будет как на сайте появляться новые торренты в списке?

**Comment by DEgITx** [comment]
может что-нибудь лучше будет, но в следующей версии, мне пока такой текущий вариант не очень нравится
