### ISSUE TITLE
How can I search with one or two words?

### ISSUE THREAD

**Issue by REFunction** [DEgITx/rats-search#110]
At first, I change the code in src/app/search.js, from 'length <3' to 'length < 1'. As a result, the 'too short...' tip is missing but I cannot get any search result, even if the search keyword is seemingly all right.

So if there are other locations needed to modify?

**Comment by DEgITx** [comment]
you also need modify sphinx.js ->
min_prefix_len = 3 - set to your value. Be careful that you need to rebuild you db to take effect or start to capturing it from begining after modification. Also the size of DB will increased

**Comment by REFunction** [comment]
> you also need modify sphinx.js ->
> min_prefix_len = 3 - set to your value. Be careful that you need to rebuild you db to take effect or start to capturing it from begining after modification. Also the size of DB will increased

Thank you for so fast reply. And could I ask how to rebuild my db?
