### ISSUE TITLE
Сервер 1.4.2 останавливается по таймауту

### ISSUE THREAD

**Issue by zarmaran** [DEgITx/rats-search#112]
При попытки соединится с p2p останавливается сервер по таймауту.
Кусочек лога:
`[p2p] new peer {
  address: '81.25.225.178',
  port: 4445,
  emit: [Function: emit],
  disconnect: [Function],
  version: '1.4.1',
  peerId: 'fhdxl3zj2ui8l58a6atfnn',
  relay: { server: true, client: false },
  info: {
    maxPeersConnections: 50,
    peersConnections: 50,
    store: 628,
    torrents: 87327,
    files: 3748611,
    filesSize: 291502010839780,
    feed: 298,
    feedDate: 1578167839
  }
}
[p2p] server connected 3 max 24

<SKIPPED>

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 81.25.225.178:36334
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '81.25.225.178',
  port: 36334
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rats-search@1.4.2 server: `node src/background/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rats-search@1.4.2 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-01-06T05_34_28_456Z-debug.log`

**Comment by SparkYDevtk** [comment]
Ага есть такое
Error: connect ETIMEDOUT 81.25.225.178:21211
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rats-search@1.4.1 server: `node src/background/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rats-search@1.4.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 Причём IP то одинаковый

**Comment by DEgITx** [comment]
какое сейчас поведение (если у вас серверная версия, просто обновитесь из мастера)

**Comment by zarmaran** [comment]
Прошло 10 часов, ошибка не появлялась. Но и сообщения "logT('relay', 'error during relay connection:', err);" в консоле нет. Видимо у пира открыли порты и соединения стали проходить
