### ISSUE TITLE
[Feature request] Add automating personal torrens from folder.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [DEgITx/rats-search#116]
There are many torrent witch is block in country and impossible to find by open search. 
But can be found in personal torrent. From persons who were quick before torrent were blocked.
So need function to auto find torrents on local computer to upload to data base.
Or to set torrents folder manually.

И спасибо, классная программа.
Но российский фильм который так интересует так и не нашёл, везде заблокирован ))

**Comment by DEgITx** [comment]
там в чем фича не очень понятно
чуть что если буду пояснения переоткрою
