### ISSUE TITLE
ports 4445 and 4446 not open using ExpressVPN

### ISSUE THREAD

**Issue by 99bobster99** [DEgITx/rats-search#118]
Hello,

Unfortunately, ExpressVPN does not seem to have ports 4445 and 4446 opened (ROTB works fine when not attached to ExpressVPN).

Are there any plans to not need these specific ports open? Can you suggest any other ideas?

**Comment by DEgITx** [comment]
You can change the port manually, otherwise program should choise another port. Reopen this issue if it still actual
