### ISSUE TITLE
[1.4.2] Ошибка отображения

### ISSUE THREAD

**Issue by DarkPlasticine** [DEgITx/rats-search#119]
При запуске программы пустое окно
![2020-04-17_16-26-48](https://user-images.githubusercontent.com/12997911/79543346-41901e80-80c8-11ea-9649-cae996f50a09.png)

**Comment by AronMav** [comment]
Та же проблема, только странно что на одном ноуте есть, а на другом нет

**Comment by AronMav** [comment]
Не знаю что было, после обновления системы до Windows 10, version 2004 все заработало.

**Comment by DarkPlasticine** [comment]
обновился до:
Выпуск	Windows 10 Pro Insider Preview
Версия	2004
Дата установки	‎29.‎01.‎2021
Сборка ОС	21301.1010
Взаимодействие	Windows Feature Experience Pack 221.501.0.3
Версия программы 1.5.0
ошибка та же
