### ISSUE TITLE
Process not killed after closing app

### ISSUE THREAD

**Issue by necros2k7** [DEgITx/rats-search#123]
subj

**Comment by viktorheli** [comment]
The same problem, but in Linux. Ubuntu 18.04. I am using rats-search-1.4.2-x86_64.AppImage.
After the client is closed, all processes remain running. If you start the client a second time, the number of processes doubles.

**Comment by Asherathe** [comment]
I noticed the same issue, also on Ubuntu-based Linux (Peppermint 10 respin), but I realized that it does eventually shut down. It just takes a looooooooong time. I presume it's closing connections and cleaning things up behind the scenes. I'm not sure if there's a way to speed up the exit process, or if maybe there should be a warning that it can take a while, so people don't kill the process manually, which seems to result in the database location being forgotten.

**Comment by DEgITx** [comment]
must be fixed in master
