### ISSUE TITLE
Программа убивает интернет после запуска

### ISSUE THREAD

**Issue by KOTOEB** [DEgITx/rats-search#138]
После запуска крыс интернет дохнет наглушняк, помогает только перезагрузка компьютера целиком. Причём по вайфаю и у других компьютеров в сети интернет есть. Видимо что-то ломается в сетевом подключении винды.

Windows 7 x64

**Comment by DEgITx** [comment]
она использует очень активно сетевые подключение, посмотрите инструкцию по поводу меньшения нагрузки сети в readme.

**Comment by KOTOEB** [comment]
А почему после закрытия программы интернет не воскресает?
