### ISSUE TITLE
npm install found 14 vulnerabilities and failed to fix/get dependency

### ISSUE THREAD

**Issue by slrslr** [DEgITx/rats-search#142]
Hello,

i am having same issue as [described here](https://forum.manjaro.org/t/npm-install-14-vulnerabilities-npm-audit-fix-could-not-resolve-dependency/63570)

Can you use newer node.js in https://github.com/DEgITx/rats-search/blob/master/.travis.yml#L7 ?

Or tell how to deal with the described issues?

**Comment by DEgITx** [comment]
why did you try to run audit fix?
it's not nessary for correct work but can be fixed in future

**Comment by slrslr** [comment]
Thanks for a reply. I thought it can fix some of the vulnerabilities [claimed to exist per the npm install command output](https://bin.disroot.org/?a1618aae0063fd92#9EHrpPgj5pGYKEUxHE1H4fZP4di2tkGrauSdaJoDrJ3j). So if i do not understand a npm and package management, you suggesting to ignore "14 vulnerabilities (6 low, 2 moderate, 6 high)" and after the "npm install" which i ran a few days ago, i now go back to the git cloned "rats-search" directory and run the:
npm run buildweb
npm run server
? Sorry i am just user, not know npm, git and such.

**Comment by DEgITx** [comment]
so yes, you don't need to make npm audit

only
npm install
npm run buildweb
npm run server

to run the web version on http://localhost:8095

**Comment by slrslr** [comment]
@DEgITx thanks, i ran it and it ended with TypeError:

```
[system] Rejection: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (7)
    at Object.writeFileSync (node:fs:1528:5)
    at setVersion (/home/lnot/apps/rats-search/src/background/dbPatcher.js:24:7)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async module.exports (/home/lnot/apps/rats-search/src/background/dbPatcher.js:468:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

[full output here](https://bin.disroot.org/?d83f78912ce7125f#ABh4LxjKnjeYXVgzjSdqgFCp1qRcg7faFk8ty3v6RfBs)

localhost:8095 web page is empty and dev console shows [these debug lines](https://i.postimg.cc/Rv4MFVPc/webconsolerats.png)

How to proceed please, any commands to try running?

**Comment by DEgITx** [comment]
> @DEgITx thanks, i ran it and it ended with TypeError:
> 
> ```
> [system] Rejection: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (7)
>     at Object.writeFileSync (node:fs:1528:5)
>     at setVersion (/home/lnot/apps/rats-search/src/background/dbPatcher.js:24:7)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
>     at async module.exports (/home/lnot/apps/rats-search/src/background/dbPatcher.js:468:3) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> ```
> 
> [full output here](https://bin.disroot.org/?d83f78912ce7125f#ABh4LxjKnjeYXVgzjSdqgFCp1qRcg7faFk8ty3v6RfBs)
> 
> localhost:8095 web page is empty and dev console shows [these debug lines](https://i.postimg.cc/Rv4MFVPc/webconsolerats.png)
> 
> How to proceed please, any commands to try running?

this one must be fixed in master, try it, if not good - reopen

**Comment by slrslr** [comment]
i tried **[this and it failed](https://bin.disroot.org/?7f2d8326bf8d07df#5G6sZwV73aFDSpiATQ8EkW9SunRNW35pCtKjryZ7qsZN)**

after i have tried to rename
node_modules/bittorrent-tracker
node_modules/semver
as it was suggesting, and ran npm install;npm run buildweb;npm run server

the "run server" command continue to complain:
/home/user/apps/rats-search/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

after renaming also this directory and re-running npm install, build, run commands:

the run server error was:
```
[system] Exception: Error: bind EADDRINUSE 0.0.0.0:4446
    at node:dgram:356:20
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 4446
} Origin: uncaughtException

[system] Exception: Error: listen EADDRINUSE: address already in use :::8095
    at Server.setupListenHandle [as _listen2] (node:net:1311:16)
    at listenInCluster (node:net:1359:12)
    at Server.listen (node:net:1446:7)
    at Object.<anonymous> (/home/user/apps/rats-search/src/background/server.js:40:8)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8095
} Origin: uncaughtException
```

"ss -p|grep 8095" shown there is node running and in "lsof -p pid" it was rats-search so i killed it: kill -9 4036476

then "npm run server" worked, while i seen only issue like:
```
[upnp] upnp server dont respond
[upnp] upnp server dont respond
[upnp] upnp server dont respond
[http] https://api.myjson.com/bins/1e5rmh abort by time

[http] https://api.myjson.com/bins/1e5rmh error: socket hang up

[replication] replicate remote torrent Рюдзо
```
([http] lines in red color)

The webUI is working except dev. console says http://localhost:8095/app.js was not found (404) possibly due to:
The resource from “http://localhost:8095/app.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

If you see what i did wrong, please let me know or
please try to prevent issues i have described, let me know if i should run some command or try something.
Thank You

**Comment by DEgITx** [comment]
you have broken node_modules folder, remove it before 
$ npm install

**Comment by slrslr** [comment]
I just did that, not ran "npm run buildweb" after that. The other issues i have:

npm run server:
```
[upnp] upnp server dont respond
[upnp] upnp server dont respond
[upnp] upnp server dont respond
[http] https://api.myjson.com/bins/1e5rmh abort by time

[http] https://api.myjson.com/bins/1e5rmh error: socket hang up

[replication] replicate remote torrent Рюдзо
```
([http] lines in red color) - maybe not important

The webUI is working except dev. console says http://localhost:8095/app.js was not found (404) possibly due to:
The resource from “http://localhost:8095/app.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

also i think that you may fix the "uncaughtException" described in my previous comment so the software instead return user friendly error or show which PID and process name is utilizing the socket (so i can kill it), i am guessing not all users would know the fix for that exception error.
