### ISSUE TITLE
1) ERR! ENOTEMPTY: directory not empty - browserslist ; 2) electron-builder: Permission denied

### ISSUE THREAD

**Issue by slrslr** [DEgITx/rats-search#144]
I have just tried to git pull origin master from https://github.com/DEgITx/rats-search.git and npm install on Manjaro Linux (Arch) and it does not complete:

```
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/user/apps/rats-search/node_modules/browserslist
npm ERR! dest /home/user/apps/rats-search/node_modules/.browserslist-vddMQixs
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/user/apps/rats-search/node_modules/browserslist' -> '/home/user/apps/rats-search/node_modules/.browserslist-vddMQixs'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-06-13T08_59_12_374Z-debug.log
```

that debug log file [is here](https://bin.disroot.org/?769705215e929d69#8DBh9m4omnegxFCtuuv9Ajj2iTUY8V8Cgr9pbFt7VfDZ).

I then renamed that folder and retry. Result:

```
sh: line 1: /home/user/apps/rats-search/node_modules/.bin/electron-builder: Permission denied
npm ERR! code 126
npm ERR! path /home/lnot/apps/rats-search
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps
```

i checked that electron-buildr file and user has rights: Access: (0777/lrwxrwxrwx)  Uid: ( 1000/    user)   Gid: ( 1001/    user)

After i have renamed whole /home/user/apps/rats-search folder and retry cloning and npm, [it finished (with deprecation warnings and vulnerabilities)](https://bin.disroot.org/?8646106339fb74ac#6nx3SUxPkcjkcV7n4VMt5LZoVwk5sgE52kwD8Ndb1GEZ) 

Please if you can check this if above issues can be prevented? Thank you @DEgITx

**Comment by DEgITx** [comment]
Which nodejs and npm version do you use? 
You xan check it with
node -v
npm -v

**Comment by slrslr** [comment]
v16.2.0
7.15.0

**Comment by DEgITx** [comment]
Remove node_modules folder fully and try again

**Comment by slrslr** [comment]
> Remove node_modules folder fully and try again

is it necessary, what output do you expect, because i have mentioned that after removing whole git folder rats-search, rats npm installed and built successfully and i am now running the rats-search...

**Comment by DEgITx** [comment]
That some not related to the app itself bug with npm, so probably not. If you can fix with simple folder remove of node_modules, thats fine.
