### ISSUE TITLE
Rats's 1.7.0 not worked on windows 10

### ISSUE THREAD

**Issue by Dicur3x** [DEgITx/rats-search#147]
Rats's 1.7.0 not worked on windows 10 (last version).
I can see processes (3 processes) but not gui started. I will rollback to 1.6.0

**Comment by Dicur3x** [comment]
Update:
reinstalled and see this (no interface):
https://imgur.com/a/7nxHsru

**Comment by DEgITx** [comment]
fixed in 1.7.1
