### ISSUE TITLE
A huge processor usage

### ISSUE THREAD

**Issue by Dicur3x** [DEgITx/rats-search#151]
On my i5-9400f there ~70% usage from this application. Too huge. I can't open it.

**Comment by Dicur3x** [comment]
Edited preferences: first was on 5. Changed to 60 and restarted - all ok.

**Comment by DEgITx** [comment]
Yes about perfomance you can read more in docs in this section, for now closing

https://github.com/DEgITx/rats-search/blob/master/docs/USAGE.md#torrent-scanner-settings
