### ISSUE TITLE
китайский, тайваньский, японский и другие языки

### ISSUE THREAD

**Issue by dreamkinRU** [DEgITx/rats-search#17]
Предлагаю убрать из наполнения базы записи не содержащие русских или латинских букв и состоящие полностью из иероглифов.

**Comment by DEgITx** [comment]
ну это для рускоговорящих юзеров, эта задача будет в большой части связанной с фильтрами сбора торрентов, может уже в следующей версии

**Comment by dreamkinRU** [comment]
> с фильтрами сбора торрентов
Вот это очень было бы круто, мне так например наполнять базу бесконечным поревом вообще не интересно. На сегодня новый ролик с клубникой появляется каждую секунду, получается что занимаемся тупо наполнением огромного мусорного бака.

**Comment by shectermen** [comment]
словари могу взять на себя

**Comment by DEgITx** [comment]
хорошо
