### ISSUE TITLE
Crashing o launch (Windows)

### ISSUE THREAD

**Issue by TuTAH1** [DEgITx/rats-search#182]
I tryed to open it, but it closes immideatly, without even showing the interface. I can only see in the task manager, that the Rats process is appears and disappears in a moment.
[rats.log](https://github.com/DEgITx/rats-search/files/10867996/rats.log)

The app works after deleting it's AppData folder

**Comment by RuikangSun** [comment]
Same issue. How did you solved? There is no AppData folder in rats search folder.

**Comment by TuTAH1** [comment]
> Same issue. How did you solved? There is no AppData folder in rats search folder.

I deleted the `%AppData%\Rats on The Boat` folder
