### ISSUE TITLE
Linux Daemon + REST API

### ISSUE THREAD

**Issue by mrx23dot** [DEgITx/rats-search#191]
My goal would be to run it on debian headless server as a 24/7 daemon and expose a REST interface?
Like search for "xy", results in json: {name, seeders, leachers, hash}, without fancy UI.

I assume running it always helps the p2p network.

Documentation only mentions glibc which I don't know how is it related to JS,
https://github.com/DEgITx/rats-search/blob/master/docs/SERVER_COMPATIBILITY.md

Is there a non javascript implementation?
Are there other projects implementing this protocol?

**Comment by DEgITx** [comment]
I will try to document it, rest api will have some limitations, because basically rats using websockets instead of rest api, but anyway as fallback I will add the support

**Comment by DEgITx** [comment]
yes

**Comment by DEgITx** [comment]
@mrx23dot, file with new doc for api is here https://github.com/DEgITx/rats-search/blob/master/docs/API.md
