### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by MotorX3Me** [DEgITx/rats-search#2]
Имя ОС	Майкрософт Windows 10 для образовательных учреждений
Версия	10.0.16299 Сборка 16299
Изготовитель ОС	Microsoft Corporation
Тип	Компьютер на базе x64
Процессор	Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz, 3301 МГц, ядер: 4, логических процессоров: 4
Версия BIOS	American Megatrends Inc. P1.40, 18.02.2011
Изготовитель основной платы	ASRock
Установленная оперативная память (RAM)	10,0 ГБ
Полный объем физической памяти	8,99 ГБ
Доступно физической памяти	6,20 ГБ
Всего виртуальной памяти	10,4 ГБ
Доступно виртуальной памяти	7,23 ГБ
Размер файла подкачки	1,38 ГБ

**Comment by DEgITx** [comment]
Есть папка c:\Users\ВАШ_ПОЛЬЗОВАТЕЛЬ\AppData\Roaming\Rats on The Boat\ вместе с содержимым?
меня в частности интересует rats.log, если он есть

**Comment by MotorX3Me** [comment]
Sphinx Path: C:\Users\Максим\AppData\Local\Programs\rats-search\searchd.exe
listening udp tracker respose on 0.0.0.0:4446
writed sphinx config to C:\Users\Максим\AppData\Roaming\Rats on The Boat
db path: C:\Users\Максим\AppData\Roaming\Rats on The Boat
sphinx: [Tue Feb  6 23:58:44.257 2018] [9416] using config file 'C:\Users\������\AppData\Roaming\Rats on The Boat/sphinx.conf'...

sphinx: [Tue Feb  6 23:58:44.258 2018] [9416] FATAL: failed to create pid file 'C:\Users\Максим\AppData\Roaming\Rats on The Boat/searchd.pid': No such file or directory

sphinx closed with code 3221226505 and signal null

**Comment by MotorX3Me** [comment]
Какой-то pid  файл не создался. Хотя во время установки ничего не вылазило.

**Comment by DEgITx** [comment]
попробуй создать пустой файл searchd.pid в этой же папке, что будет после запуска теперь?

**Comment by MotorX3Me** [comment]
Не помогла не в этой же папке нив папке самой программы.

**Comment by MotorX3Me** [comment]
Может бтника не хватает какого нибудь при запуске?

**Comment by DEgITx** [comment]
Я нешел проблему, подожди версию 0.3.1, я там поправлю этот случай

**Comment by MotorX3Me** [comment]
Ок, когда ждать счастья? И ещё вопрос. Я не читал предыдущие посты, но так догадываюсь что есть проблема с роутерами?

**Comment by DEgITx** [comment]
через час наверное где-то поправлю

**Comment by MotorX3Me** [comment]
Ок.

**Comment by DEgITx** [comment]
Проблема с портами имеешь ввиду?

**Comment by MotorX3Me** [comment]
Да

**Comment by MotorX3Me** [comment]
Кстати, ты музыку пишешь?

**Comment by DEgITx** [comment]
https://github.com/DEgITx/rats-search/releases/download/v0.3.1/Rats.on.The.Boat.Setup.0.3.1.exe
попробуй, должно работать сейчас

**Comment by MotorX3Me** [comment]
Минуту

**Comment by MotorX3Me** [comment]
Всё. Вроде заработало. Удалил прогу, затёр реестр (на всякий случай) и поставил эту.

**Comment by DEgITx** [comment]
хорошо

**Comment by MotorX3Me** [comment]
Кстати, Русский язык предвидится?

**Comment by DEgITx** [comment]
предвидится, но пока не в приоритете

**Comment by MotorX3Me** [comment]
А хотелось бы)) Спасибо за прогу! 
Кстати. Тоже пишу музыку. Меня можно найти в вк https://vk.com/motorx3me

**Comment by DEgITx** [comment]
взгляну)
