### ISSUE TITLE
Словари , Темы 

### ISSUE THREAD

**Issue by shectermen** [DEgITx/rats-search#20]
что могу 
1) Привести стили в порядок 
2) Сделать отдельный механизм тем (любой кто умеет верстать сможет сделать свою собственную тему )
3) Сделать словари, запилю английский и русский , ну и механизм загрузки новых языков

ну и в целом могу помогать с фиксами, я б еще лендинг презентационный  сделал для народа 

еще есть идея как сделать мини презентацию в самом начале и предложение скачать базу торрентов с гугл диска например или какого другого хоста , ибо многие с первого раза не понимают как вообще пользоваться (у меня кстати БД все еще не растет сама по себе ) и переработать интерфейс технический который показывает пиров, сидов , порты и все прочее, чтобы поудобнее было

**Comment by DEgITx** [comment]
ну отлично, только держи меня вкурсе четко по статусу что делаешь, если берешься, чтобы не пересекалось и т.п., если будут возникать любые вопросы, может где угодно меня выцепить degitx (телеграм, вк, дискорд, иногда скайп)

Насчет фишки с предложением скачать базу - у меня была такая мысль, не знаю насколько нужно, но это тоже отдельная таска, которую нужно обсуждать - потому что сам клиент должен быть чистый, а базы и хостинги баз могут отрубаться и т.п. У меня была мысль еще подружать базу целиком у через p2p у какого-то определенного пира (например с самой большой базой). Но пиры непостоянны и тоже свои нюансы есть.

**Comment by Taran2ul** [comment]
Может быть хотябы добавить информацию о базе. Например, 77Тб из 500Тб.

**Comment by dreamkinRU** [comment]
Я уже предлагал сделать хоть какую статистику. Отдельной страницей например, сколько всего в общей базе, сколько процентов у меня и т. д.

**Comment by DEgITx** [comment]
Переводы появились в новой версии из master
