### ISSUE TITLE
Linux x86

### ISSUE THREAD

**Issue by Flashwalker** [DEgITx/rats-search#21]
Зопели под линь 32 бита.

**Comment by shectermen** [comment]
это ж электрон , можешь спулить и скомпилять под свою систему сам

**Comment by DEgITx** [comment]
Там не так все просто, есть один бинарный компонент для базы который используется, он в бинарном виде поэтому для каждой системы отдельно нужно запиливать, я наверное в ближайшее время включу его для линя и для x86
