### ISSUE TITLE
Проблемы с поиском

### ISSUE THREAD

**Issue by Taran2ul** [DEgITx/rats-search#24]
Версия 0.17.0 Portable
Вчера база была 20Тб. Искал "FBReader" нашлось сколько-то торрентов.
Сегодня база 75Тб. Проверка поиска "FBReader". Найдено 0.
Как? Почему? Что делать?

**Comment by DEgITx** [comment]
в 0.7.1 будет кое какое исправление касательно локальный баз, в ней наверное лучше искать будет

**Comment by DEgITx** [comment]
![image](https://user-images.githubusercontent.com/207785/38316232-eb586660-3832-11e8-9d0a-6fabd296fe0f.png)
на удаленных узнал вроде что-то есть

**Comment by Taran2ul** [comment]
Ага. Сегодня находит.
