### ISSUE TITLE
Фильтрация через RegExp

### ISSUE THREAD

**Issue by dreamkinRU** [DEgITx/rats-search#25]
Добавьте хоть какой микроредактор, со списком фраз для исключения, и диапазонами символов.
Саму строку удобнее видеть в виде выпадающего списка из последних использованых наборов с возможностью быстрого редактирования.
Не очень удобно отдельно в файле сохранять строки и потом копипастить.

**Comment by DEgITx** [comment]
я пока базовый селект сделал, если кто напридумывает каких-то вариантов - можно будет усложнить
