### ISSUE TITLE
JavaScript error при попытке проголосовать

### ISSUE THREAD

**Issue by evgen-gruzinov** [DEgITx/rats-search#27]
![default](https://user-images.githubusercontent.com/31236823/38465910-10eec050-3b2a-11e8-998f-e8716e492bc4.PNG)

**Comment by DEgITx** [comment]
это какая версия, в последней вроде как сообщение о том что нельзя голосовать выскакивает

**Comment by evgen-gruzinov** [comment]
Старая уже, 16.2.
Можно закрывать
