### ISSUE TITLE
При нажатии на кнопку "Загрузки" появляется только белый экран

### ISSUE THREAD

**Issue by Derr22** [DEgITx/rats-search#34]
![default](https://user-images.githubusercontent.com/35798877/41560296-5fa7d850-734f-11e8-8f01-071e3a670c6e.png)

**Comment by DEgITx** [comment]
какая версия операционной системы?

**Comment by Derr22** [comment]
Windows 10 64x 1607

**Comment by DEgITx** [comment]
должно более менее работать в 0.21.1
