### ISSUE TITLE
Странно выглядит не в полном размере

### ISSUE THREAD

**Issue by CoderFF** [DEgITx/rats-search#40]
Ubuntu 16.04.
Запускается в таком размере. При переключении кнопок FEED/TOP/DOWNLOAD/ACTIVITTY инонки на этих кнопках меняют своё положение относительно кнопки. Если развернуть на полный экран, то всё норм.
![2018-07-10 23-57-01](https://user-images.githubusercontent.com/22940410/42537329-3e48c502-849d-11e8-877b-ee1fcda11a22.png)

**Comment by DEgITx** [comment]
а что конкретно считаете странным? то что вылазят название кнопок вниз, или что-то другое?

**Comment by DEgITx** [comment]
ясно, ну хорошо, я подумаю если что-нибудь элегантное придумаю с этим скролом - то поправлю

**Comment by CoderFF** [comment]
Да я понимаю, что это минорная проблема, просто это то, что сразу бросается в глаза.
