### ISSUE TITLE
Уведомление о новой версии для портативок

### ISSUE THREAD

**Issue by NoAdO** [DEgITx/rats-search#41]
Поскольку судя по комменту https://pikabu.ru/story/torrent_poiskovik_piratskiy_den_6016682?cid=116996483 портативки не обновляются было бы неплохо если бы люди могли хотя бы узнать о том что новая версия доступна для скачивания.

P.S. Не знаю как тут определить баг или фича, поэтому создал уж как есть.

**Comment by DEgITx** [comment]
в 0.25.0 портативке уже будет )
