### ISSUE TITLE
Проброс портов на роутере Zyxel Keenetic 4G II

### ISSUE THREAD

**Issue by dreamkinRU** [DEgITx/rats-search#5]
Не работает проброска портов на сабже. Испробованные варианты: только TCP 4445-4446, только UDP 4445-4446 и оба варианта сразу.
Довольно странно вообще заниматься этим, учитывая что любой торрент-клиент и DC у меня настраиваются автоматом через UPnP протокол.

**Comment by DEgITx** [comment]
В следующих версиях может возможно появиться поддержка и UPnP. У меня к примеру роутер некорректно с UPnP работает и не пробрасывает до конца UDP порты. Кстати желательно оба типа пробрасывать сразу.
Можете ради интереса попробовать отключить UPnP в торрент клиенте и настроить на открытый порт, если порт действительно открыт то должно через него находить торренты по магнет ссылками - если же порт закрыт, то вероятнее всего не будет - так, к примеру, можно удостовериться открыт ли он на самом деле. На действительно открытом порте и торрент-клиент должен работать, и крысы. Это конечно все в случае если нет каких-либо ограничений после - типо еще всяких NAT от провайдера.
Но а так я пока ставлю на проблему с пробросом.

**Comment by DEgITx** [comment]
Попробуй последнюю версию, я там добавил поддержку UPnP

**Comment by dreamkinRU** [comment]
Отличная работа бро!
На всякий случай, если у кого останется такая же проблема после обновления, вот что я сделал:
в настройках задал произвольные порты 4455 и 4456, сохранил, перезапустил, опять в настройки и вернул как должно было быть 4445 и 4446, сохранил. Всё заработало!

**Comment by dreamkinRU** [comment]
А то что в нижней строчке "rats peers: 0 (p2p rats search not available at this moment)"
Это нормально?

**Comment by DEgITx** [comment]
Да вполне
