### ISSUE TITLE
Странные торренты в поиске

### ISSUE THREAD

**Issue by CoderFF** [DEgITx/rats-search#52]
По запросу "приключений"

![2018-07-23 17-09-36](https://user-images.githubusercontent.com/22940410/43081863-47c01952-8e9b-11e8-86c1-4176bd7e514c.png)

Выводит странные торренты

NaN undefined (undefined files)
Планета приключений/1-2. Планета приключений (пер. Тишинин).fb2
Планета приключений/1-4. Планета приключений.fb2

NaN undefined (undefined files)
Берндорф Ганс, Букар Робер - (В мире приключений) Сети шпионажа [Сборник].fb2

NaN undefined (undefined files)
2002 - Форева/09 - Жажда приключений.mp3
2004 - Живой и невридимый/12 - Жажда Приключений.mp3
2002 - Форева/09 - Жажда приключений.mp3

magnet ссылка у всех magnet:?xt=urn:btih:undefined

При попытке кликнуть на такой торрент, приложение крэшится
Вот что в логах

```
/home/coder/workspace/rats-search/src/background/api.js:128
		if(hash.length != 40)
		        ^

TypeError: Cannot read property 'length' of null
    at onTorrent (/home/coder/workspace/rats-search/src/background/api.js:128:11)
    at Socket.args (/home/coder/workspace/rats-search/src/background/api.js:76:9)
    at emitThree (events.js:136:13)
    at Socket.emit (events.js:217:7)
    at /home/coder/workspace/rats-search/node_modules/socket.io/lib/socket.js:527:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Из базы данных вот что выяснил:

```
mysql> select * from files where MATCH('приключений') limit 1;
+---------+---------+---------------------------------------------------------------------------------------------------------------+------------------------------------------+
| id      | size    | path                                                                                                          | hash                                     |
+---------+---------+---------------------------------------------------------------------------------------------------------------+------------------------------------------+
| 2414876 | 1409369 | Планета приключений/1-2. Планета приключений (пер. Тишинин).fb2                                               | 12c0cfd6e2bad8ba116c883d48ca0ca5f0bf3f14 |
+---------+---------+---------------------------------------------------------------------------------------------------------------+------------------------------------------+
1 row in set (0,02 sec)

mysql> select * from torrents where hash='12c0cfd6e2bad8ba116c883d48ca0ca5f0bf3f14' limit 1;
Empty set (0,02 sec)

```
Я так понимаю, что после выполнения операции "CLEAN TORRENTS" сложилась такая ситуация, что торрент удалён, а файлы от него - нет.

**Comment by DEgITx** [comment]
В общем там из-за прерывания очистки такое в целом могло произойти, в следующей версии уже поправлю, заодно более активный индикатор прицеплю, а то совершенно не видно как оно чистит

**Comment by CoderFF** [comment]
Уверен, что не выходил. 
Он выстветил цифру, сколько удалил торрентов + еще долго после этого работал, я так понимаю он продолжает удалять в фоновом режиме. Нарузка на проц от searchd была на 100% еще долго (хотя может быть, активный обмен торрентами).

Что хочу добавить, это догадка, может быть мимо абсолютно. При старте приложения довольно долго выполняется вот такое действие:

sphinx: binlog: replaying log /home/coder/workspace/rats-search/binlog.001

sphinx: binlog: index torrents: recovered from tid 427467 to tid 488878
binlog: index files: skipped at tid 7828127 and max binlog tid 6437868
binlog: replay stats: 818766 rows in 819391 commits; 34219 updates, 0 reconfigure; 2 indexes

```
sphinx: binlog: finished replaying /home/coder/workspace/rats-search/binlog.001; 240.9 MB in 2.476 sec
binlog: replaying log /home/coder/workspace/rats-search/binlog.002

sphinx: binlog: index torrents: recovered from tid 488878 to tid 500536
binlog: index files: skipped at tid 7828127 and max binlog tid 6557804
binlog: replay stats: 124213 rows in 124264 commits; 7330 updates, 0 reconfigure; 2 indexes
binlog: finished replaying /home/coder/workspace/rats-search/binlog.002; 35.2 MB in 0.385 sec
binlog: replaying log /home/coder/workspace/rats-search/binlog.003
 
```
Что по этому поводу пишут в документации от searchd:

> Binary logs are essentially a recovery mechanism. With binary logs enabled, searchd writes every given transaction to the binlog file, and uses that for recovery after an unclean shutdown. On clean shutdown, RAM chunks are saved to disk, and then all the binlog files are unlinked.

То есть, при нормальном завершении работы searchd, этих бинлогов вообще быть не должно, а у меня они постоянно! Выходит, какое-то повреждение БД возможно.

В таком случае возникает вопрос, каким образом можно завершить работу серверного rats-search так, чтобы и searchd завершил работу нормально? Я запускаю так

`nvm exec lts/carbon npm run server`

Завершаю - Ctrl+C

**Comment by DEgITx** [comment]
У серверной версии в отличии от десктопной нет нормальной обработки выхода, ctrl+с в любом случае резко прерывает работу скрипта, ни о каком корректном завершении там говорить не приходится, запиши насчет этого в отдельный тикет, я хотел с этим разобраться, но подзабыл... насчет этой же проблемы - это не из-за этого, я там сделаю комит на днях, который с этой проблемой должен разобраться

**Comment by DEgITx** [comment]
в 7e0c565 поправлен сам механизм очистки) (возможно поправлен)
но это не касается тех торрентов которые уже хреново чистануло

**Comment by DEgITx** [comment]
должно сейчас корректно в серверной версии выходить
