### ISSUE TITLE
При старте, проверять что searchd запущен

### ISSUE THREAD

**Issue by CoderFF** [DEgITx/rats-search#53]
Иногда, если приложение вылетает, его невозможно запустить заново.
Натыкался на такое в #52 , #45.
Так или иначе, бывает приложение закрывается. При повторном запуске, в логах это:

`sphinx closed with code 1 and signal null`
Дальше приложение висит, не может выйти но и не может показать интерфейс: при заходе на http://localhost:8095/ вижу белую страницу, если открыть код то там

`<!DOCTYPE html><html><head><meta charset="utf-8"><title>Torrent Search</title></head><body><div id="mount-point"></div><script src="app.js"></script><script type="text/javascript" src="main.js"></script></body></html>`

Я обнаружил, что при этом процесс searchd продолжает работать, принимает соединения и обрабатывает запросы. 
Это лечится снятием процесса searchd
`killall searchd`
И повторным запуском rat-search

Я предполагаю, что при падении, rats-search не успевает закрыть searchd, но при старте ждёт нормального его старта. Я предположил, что searchd не может запуститься из-за EADDRINUSE. Ни подтверждения, ни опровержения в searchd.log я не нашёл, никаких записей за это время там нет.

Попытался запустить searchd вручную.

```
$ /home/coder/workspace/rats-search/imports/linux/x64/searchd --config /home/coder/workspace/rats-search/sphinx.conf --nodetach
Manticore 2.6.1 a7fa71e@180126 release
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2018, Manticore Software LTD (http://manticoresearch.com)

using config file '/home/coder/workspace/rats-search/sphinx.conf'...
listening on all interfaces, port=9312
listening on all interfaces, port=9306
precaching index 'torrents'
WARNING: index 'torrents': prealloc: failed to lock /home/coder/workspace/rats-search/database/torrents.lock: Resource temporarily unavailable; NOT SERVING
precaching index 'files'
WARNING: index 'files': prealloc: failed to lock /home/coder/workspace/rats-search/database/files.lock: Resource temporarily unavailable; NOT SERVING
precaching index 'version'
WARNING: index 'version': prealloc: failed to lock /home/coder/workspace/rats-search/database/version.lock: Resource temporarily unavailable; NOT SERVING
precaching index 'store'
WARNING: index 'store': prealloc: failed to lock /home/coder/workspace/rats-search/database/store.lock: Resource temporarily unavailable; NOT SERVING
precaching index 'feed'
WARNING: index 'feed': prealloc: failed to lock /home/coder/workspace/rats-search/database/feed.lock: Resource temporarily unavailable; NOT SERVING
FATAL: no valid indexes to serve
shutdown complete

```

Похоже, лучшее поведение в данной ситуации - не пытаться запускать searchd, если он уже запущен. Либо убивать старый и запускать новый.

**Comment by DEgITx** [comment]
проверь бывает ли сейчас так что остается searchd, в серверной версии изменился порядок выхода, и бывает ли подобное в десктоп версии?

**Comment by vGimly** [comment]
Для отладки наоборот даже полезно запускать демона searchd отдельно от процесса.
Например так:  #57
