### ISSUE TITLE
Бесконечный Peer Exchange

### ISSUE THREAD

**Issue by vGimly** [DEgITx/rats-search#56]
Регулярно наблюдаю картинку, что некоторые пиры начинают непрерывно слать pex одних и тех же пиров - без остановки. (samehost это один и тот же ip)
запись tcpdump только от внешнего пира (evil) в приложении

[tcpdump-pex.txt](https://github.com/DEgITx/rats-search/files/2261797/tcpdump-pex.txt)

**Comment by DEgITx** [comment]
известный баг, он не критичный и на работу никак не сказывается, но нужно будет поправить

**Comment by DEgITx** [comment]
в 1.2.0 должно быть исправлено
