### ISSUE TITLE
Работа под MacOs

### ISSUE THREAD

**Issue by Exlatus** [DEgITx/rats-search#58]
С последним релизом программа запускается окном "Database patching...", и может так висеть вечность. При этом скачивает из инета 6.3 мегабайта и выгружает в сеть 2.5 мегабайта.

**Comment by Exlatus** [comment]
[rats.log](https://github.com/DEgITx/rats-search/files/2351797/rats.log)
Высылаю

**Comment by DEgITx** [comment]
пробовали перезагрузиться или убить процесс searchd перез запуском, или подобное происходит при первом запуске?

**Comment by Exlatus** [comment]
После перезагрузки такая же фигня. 
Процесс убивать не пробовал.
Раньше была установлена какая-то версия, релизом точно ниже, чем сейчас пытаюсь запустить.

**Comment by DEgITx** [comment]
проблема еще актуально, так и не запустилось в итоге?

**Comment by Exlatus** [comment]
Да, еще актуально. Все еще не пашет.

**Comment by Helpfulpaw** [comment]
После убийства процессов и searchd свежий запуск корректно отработал
