### ISSUE TITLE
Не добавляются торренты

### ISSUE THREAD

**Issue by kttyt** [DEgITx/rats-search#6]
За время работы был найден только один торрент. Порты из вкладки config(4445; 4446) на роутере проброшены, однако в файле sphinx.conf указаны другие порты(9312; 9306), нужно ли их пробрасывать?

> ./rats-search-0.9.0-x86_64.AppImag
> installed: X-AppImage-BuildId=5f4474f0-1db8-11a8-0dc9-2d8caa32576f image: X-AppImage-BuildId=5f4474f0-1db8-11a8-0dc9-2d8caa32576f
> Rats 0.9.0
> Platform: linux
> Arch: x64
> OS Release: 4.12.12-gentoo
> CPU: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
> CPU Logic cores: 4
> Total memory: 3610.97 MB
> Free memory: 373.86 MB
> Sphinx Path: /tmp/.mount_rats-sr1jikN/app/searchd
> listening udp tracker respose on 0.0.0.0:4446
> writed sphinx config to /home/USER/.config/Rats on The Boat
> db path: /home/USER/.config/Rats on The Boat
> sphinx: [Fri Mar  2 16:37:57.185 2018] [10984] using config file '/home/USER/.config/Rats on The Boat/sphinx.conf'...
> 
> sphinx: listening on all interfaces, port=9312
> listening on all interfaces, port=9306
> 
> sphinx: Manticore 2.6.1 a7fa71e@180126 release
> Copyright (c) 2001-2016, Andrew Aksyonoff
> Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
> Copyright (c) 2017-2018, Manticore Software LTD (http://manticoresearch.com)
> 
> precaching index 'torrents'
> 
> sphinx: precaching index 'files'
> 
> sphinx: WARNING: index 'statistic': no fields configured (use rt_field directive) - NOT SERVING
> binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.001
> 
> sphinx: binlog: index torrents: recovered from tid 0 to tid 3
> binlog: index files: recovered from tid 0 to tid 1
> binlog: replay stats: 2 rows in 2 commits; 2 updates, 0 reconfigure; 2 indexes
> binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.001; 0.0 MB in 0.000 sec
> binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.002
> 
> sphinx: binlog: replay stats: 0 rows in 0 commits; 0 updates, 0 reconfigure; 0 indexes
> binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.002; 0.0 MB in 0.000 sec
> binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.003
> binlog: replay stats: 0 rows in 0 commits; 0 updates, 0 reconfigure; 0 indexes
> binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.003; 0.0 MB in 0.000 sec
> binlog: finished replaying total 3 in 0.000 sec
> 
> sphinx: accepting connections
> 
> catched sphinx start
> listen p2p on 4445 port
> Listen DHT protocol on 0.0.0.0:4445
> Checking for update
> sphinx: prereading 2 indexes
> prereaded 2 indexes in 0.000 sec
> 
> p2p stun ignore my address [Внешний адрес провайдера]
> p2p upnp ignore my address [Адрес моего роутера в локальной сети провайдера]
> Update for version 0.9.0 is not available (latest version: 0.9.0, downgrade is disallowed.

query.log
> [Fri Mar  2 16:15:38.087 2018] 0.009 sec 0.009 sec [ext2/0/ext 0 (0,20)] [torrents]
> [Fri Mar  2 16:15:38.093 2018] 0.000 sec 0.000 sec [ext2/0/ext 0 (0,20)] [files]
> [Fri Mar  2 16:15:39.041 2018] 0.000 sec 0.000 sec [ext2/0/ext 0 (0,20)] [torrents]
> [Fri Mar  2 16:15:39.042 2018] 0.001 sec 0.001 sec [ext2/0/ext 0 (0,10)] [torrents]
> [Fri Mar  2 16:15:39.044 2018] 0.000 sec 0.000 sec [ext2/0/ext 0 (0,20)] [files]
> [Fri Mar  2 16:16:12.441 2018] 0.007 sec 0.007 sec [ext2/0/ext 0 (0,20)] [torrents]
> [Fri Mar  2 16:16:12.452 2018] 0.000 sec 0.000 sec [ext2/0/ext 0 (0,20)] [files]
> [Fri Mar  2 16:16:13.376 2018] 0.000 sec 0.000 sec [ext2/0/ext 0 (0,20)] [files]
> [Fri Mar  2 16:16:22.489 2018] 0.000 sec 0.000 sec [ext2/0/ext 0 (0,20)] [files]
> [Fri Mar  2 16:22:57.628 2018] 0.000 sec 0.000 sec [ext2/1/ext 0 (0,20)] [files]
> [Fri Mar  2 16:22:57.635 2018] 0.000 sec 0.000 sec [ext2/1/ext 0 (0,20)] [torrents]
> [Fri Mar  2 16:22:57.635 2018] 0.000 sec 0.000 sec [ext2/1/ext 0 (0,20)] [files]
> [Fri Mar  2 16:22:57.638 2018] 0.000 sec 0.000 sec [ext2/1/ext 1 (0,20)] [torrents]
> [Fri Mar  2 16:22:57.902 2018] 0.000 sec 0.000 sec [ext2/1/ext 1 (0,20)] [torrents]
> [Fri Mar  2 16:29:08.329 2018] 0.010 sec 0.010 sec [ext2/0/ext 1 (0,20)] [torrents]
> [Fri Mar  2 16:29:08.359 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [files]
> [Fri Mar  2 16:29:09.315 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [torrents]
> [Fri Mar  2 16:29:09.316 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,10)] [torrents]
> [Fri Mar  2 16:29:09.321 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [files]
> [Fri Mar  2 16:31:07.972 2018] 0.000 sec 0.000 sec [ext2/2/ext 1 (0,20)] [torrents]
> [Fri Mar  2 16:31:07.990 2018] 0.000 sec 0.000 sec [ext2/3/ext 0 (0,15)] [torrents]
> [Fri Mar  2 16:31:07.991 2018] 0.000 sec 0.000 sec [ext2/3/ext 0 (0,15)] [torrents]
> [Fri Mar  2 16:31:07.992 2018] 0.000 sec 0.000 sec [ext2/3/ext 0 (0,15)] [torrents]
> [Fri Mar  2 16:31:11.583 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [torrents]
> [Fri Mar  2 16:31:11.583 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,10)] [torrents]
> [Fri Mar  2 16:31:11.587 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [files]
> [Fri Mar  2 16:37:57.728 2018] 0.010 sec 0.010 sec [ext2/0/ext 1 (0,20)] [torrents]
> [Fri Mar  2 16:37:57.760 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [files]
> [Fri Mar  2 16:37:58.733 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [files]
> [Fri Mar  2 16:42:01.106 2018] 0.000 sec 0.000 sec [ext2/0/ext 1 (0,20)] [files]

 searchd.log
> [Fri Mar  2 16:15:37.499 2018] [8186] listening on all interfaces, port=9312
> [Fri Mar  2 16:15:37.499 2018] [8186] listening on all interfaces, port=9306
> [Fri Mar  2 16:15:37.511 2018] [8186] WARNING: index 'statistic': no fields configured (use rt_field directive) - NOT SERVING
> [Fri Mar  2 16:15:37.511 2018] [8186] accepting connections
> [Fri Mar  2 16:15:37.512 2018] [8198] prereading 2 indexes
> [Fri Mar  2 16:15:37.512 2018] [8198] prereaded 2 indexes in 0.000 sec
> [Fri Mar  2 16:16:06.739 2018] [8186] caught SIGTERM, shutting down
> [Fri Mar  2 16:16:06.765 2018] [8186] shutdown complete
> [Fri Mar  2 16:16:11.870 2018] [8314] listening on all interfaces, port=9312
> [Fri Mar  2 16:16:11.870 2018] [8314] listening on all interfaces, port=9306
> [Fri Mar  2 16:16:11.881 2018] [8314] WARNING: index 'statistic': no fields configured (use rt_field directive) - NOT SERVING
> [Fri Mar  2 16:16:11.881 2018] [8314] accepting connections
> [Fri Mar  2 16:16:11.881 2018] [8326] prereading 2 indexes
> [Fri Mar  2 16:16:11.881 2018] [8326] prereaded 2 indexes in 0.000 sec
> [Fri Mar  2 16:24:57.531 2018] [9383] listening on all interfaces, port=9312
> [Fri Mar  2 16:24:57.531 2018] [9383] listening on all interfaces, port=9306
> [Fri Mar  2 16:24:57.542 2018] [9383] WARNING: index 'statistic': no fields configured (use rt_field directive) - NOT SERVING
> [Fri Mar  2 16:24:57.542 2018] [9383] binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.001
> [Fri Mar  2 16:24:57.544 2018] [9383] binlog: index torrents: recovered from tid 0 to tid 3
> [Fri Mar  2 16:24:57.544 2018] [9383] binlog: index files: recovered from tid 0 to tid 1
> [Fri Mar  2 16:24:57.544 2018] [9383] binlog: replay stats: 2 rows in 2 commits; 2 updates, 0 reconfigure; 2 indexes
> [Fri Mar  2 16:24:57.544 2018] [9383] binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.001; 0.0 MB in 0.001 sec
> [Fri Mar  2 16:24:57.544 2018] [9383] binlog: finished replaying total 1 in 0.001 sec
> [Fri Mar  2 16:24:57.544 2018] [9383] accepting connections
> [Fri Mar  2 16:24:57.544 2018] [9395] prereading 2 indexes
> [Fri Mar  2 16:24:57.544 2018] [9395] prereaded 2 indexes in 0.000 sec
> [Fri Mar  2 16:29:07.774 2018] [9878] listening on all interfaces, port=9312
> [Fri Mar  2 16:29:07.774 2018] [9878] listening on all interfaces, port=9306
> [Fri Mar  2 16:29:07.785 2018] [9878] WARNING: index 'statistic': no fields configured (use rt_field directive) - NOT SERVING
> [Fri Mar  2 16:29:07.785 2018] [9878] binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.001
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: index torrents: recovered from tid 0 to tid 3
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: index files: recovered from tid 0 to tid 1
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: replay stats: 2 rows in 2 commits; 2 updates, 0 reconfigure; 2 indexes
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.001; 0.0 MB in 0.001 sec
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.002
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: replay stats: 0 rows in 0 commits; 0 updates, 0 reconfigure; 0 indexes
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.002; 0.0 MB in 0.000 sec
> [Fri Mar  2 16:29:07.787 2018] [9878] binlog: finished replaying total 2 in 0.001 sec
> [Fri Mar  2 16:29:07.787 2018] [9878] accepting connections
> [Fri Mar  2 16:29:07.787 2018] [9890] prereading 2 indexes
> [Fri Mar  2 16:29:07.787 2018] [9890] prereaded 2 indexes in 0.000 sec
> [Fri Mar  2 16:37:57.191 2018] [10984] listening on all interfaces, port=9312
> [Fri Mar  2 16:37:57.191 2018] [10984] listening on all interfaces, port=9306
> [Fri Mar  2 16:37:57.202 2018] [10984] WARNING: index 'statistic': no fields configured (use rt_field directive) - NOT SERVING
> [Fri Mar  2 16:37:57.202 2018] [10984] binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.001
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: index torrents: recovered from tid 0 to tid 3
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: index files: recovered from tid 0 to tid 1
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: replay stats: 2 rows in 2 commits; 2 updates, 0 reconfigure; 2 indexes
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.001; 0.0 MB in 0.000 sec
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.002
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: replay stats: 0 rows in 0 commits; 0 updates, 0 reconfigure; 0 indexes
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.002; 0.0 MB in 0.000 sec
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: replaying log /home/USER/.config/Rats on The Boat/binlog.003
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: replay stats: 0 rows in 0 commits; 0 updates, 0 reconfigure; 0 indexes
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: finished replaying /home/USER/.config/Rats on The Boat/binlog.003; 0.0 MB in 0.000 sec
> [Fri Mar  2 16:37:57.203 2018] [10984] binlog: finished replaying total 3 in 0.000 sec
> [Fri Mar  2 16:37:57.204 2018] [10984] accepting connections
> [Fri Mar  2 16:37:57.205 2018] [10996] prereading 2 indexes
> [Fri Mar  2 16:37:57.205 2018] [10996] prereaded 2 indexes in 0.000 sec

sphinx.conf
```
  index torrents
  {
    type = rt
    path = /home/USER/.config/Rats on The Boat/database/torrents
    
    rt_attr_string = hash
    rt_attr_string = name
    rt_field = nameIndex
    rt_attr_bigint = size
    rt_attr_uint = files
    rt_attr_uint = piecelength
    rt_attr_timestamp = added
    rt_attr_string = ipv4
    rt_attr_uint = port
    rt_attr_string = contentType
    rt_attr_string = contentCategory
    rt_attr_uint = seeders
    rt_attr_uint = leechers
    rt_attr_uint = completed
    rt_attr_timestamp = trackersChecked
    rt_attr_uint = good
    rt_attr_uint = bad
  }

  index files
  {
      type = rt
      path = /home/USER/.config/Rats on The Boat/database/files
      
      rt_attr_string = path
      rt_field = pathIndex
    rt_attr_string = hash
    rt_attr_bigint = size
  }

  index statistic
  {
      type = rt
      path = /home/USER/.config/Rats on The Boat/database/statistic
      
    rt_attr_bigint = size
    rt_attr_bigint = files
    rt_attr_uint = torrents
  }

  searchd
  {
    listen      = 9312
    listen      = 9306:mysql41
    read_timeout    = 5
    max_children    = 30
    seamless_rotate   = 1
    preopen_indexes   = 1
    unlink_old    = 1
    workers     = threads # for RT to work
    pid_file    = /home/USER/.config/Rats on The Boat/searchd.pid
    log     = /home/USER/.config/Rats on The Boat/searchd.log
    query_log   = /home/USER/.config/Rats on The Boat/query.log
    binlog_path = /home/USER/.config/Rats on The Boat
  }
```

**Comment by DEgITx** [comment]
А ваш роутер не обесечивает выход в интернет?

**Comment by kttyt** [comment]
Обеспечивает. Проблема вряд ли в нем, при подключении напрямую (провайдерским штекером прямо в ноут) проблема сохраняется.

**Comment by DEgITx** [comment]
Я уточню - там где внешний адрес провайдера - именно ваш адресс в интернете? Или вдруг у провайдера один адресс на всех (я просто знавал таких провайдеров)

**Comment by kttyt** [comment]
Не могу утверждать, что внешним адресом пользуюсь только я. Но судя по пулу https://bgp.he.net/AS8369#_prefixes у провайдера достаточно адресов.

**Comment by kttyt** [comment]
В версии 0.13.0 появились пиры и скорость поиска торрентов значительно увеличилась.
