### ISSUE TITLE
Server build problem (spawn ENOENT)

### ISSUE THREAD

**Issue by dongha28** [DEgITx/rats-search#66]
When I attempt to install rats search following the instructions on the README.md, the install fails at the 'npm run server' step. My system is a ODROID-C2 (arm64).

**Output from 'npm run server'**

> rats-search@1.0.0 server /home/ratse/rats-search
> node src/background/server.js

[system] Rats v1.0.0
[system] Listening web server on 8095 port
[system] Platform: linux
[system] Arch: arm64
[system] OS Release: 3.16.60+
[system] CPU: unknown
[system] CPU Logic cores: 4
[system] Total memory: 1984.32 MB
[system] Free memory: 123.92 MB
[system] NodeJS: v8.14.0
[sphinx] Sphinx Path: /home/ratse/rats-search/searchd
[udp-tracker] listening udp tracker respose on 0.0.0.0:4446
[sphinx] writed sphinx config to /home/ratse/rats-search
[sphinx] db path: /home/ratse/rats-search
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/ratse/rats-search/searchd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rats-search@1.0.0 server: `node src/background/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rats-search@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ratse/.npm/_logs/2018-12-13T15_04_45_921Z-debug.log

**Output from 'debug.log'**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'server' ]
2 info using npm@6.4.1
3 info using node@v8.14.0
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle rats-search@1.0.0~preserver: rats-search@1.0.0
6 info lifecycle rats-search@1.0.0~server: rats-search@1.0.0
7 verbose lifecycle rats-search@1.0.0~server: unsafe-perm in lifecycle true
8 verbose lifecycle rats-search@1.0.0~server: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/r$
9 verbose lifecycle rats-search@1.0.0~server: CWD: /home/ratse/rats-search
10 silly lifecycle rats-search@1.0.0~server: Args: [ '-c', 'node src/background/server.js' ]
11 silly lifecycle rats-search@1.0.0~server: Returned: code: 1  signal: null
12 info lifecycle rats-search@1.0.0~server: Failed to exec server script
13 verbose stack Error: rats-search@1.0.0 server: `node src/background/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rats-search@1.0.0
15 verbose cwd /home/ratse/rats-search
16 verbose Linux 3.16.60+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
18 verbose node v8.14.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error rats-search@1.0.0 server: `node src/background/server.js`
22 error Exit status 1
23 error Failed at the rats-search@1.0.0 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DEgITx** [comment]
Rats now have not supported arm64, may be future version will support, all depends on one internal component

**Comment by dongha28** [comment]
Ah okay, hopefully, I can run rats-search on ARM devices in the future...
Thanks for the quick reply 👍

**Comment by DEgITx** [comment]
Can you test test from master? Maybe it will work now.

**Comment by dongha28** [comment]
I'll give it a run sometime today on the same system and post results!

**Comment by DEgITx** [comment]
test now again :)
