### ISSUE TITLE
Javascript error после последнего обновления

### ISSUE THREAD

**Issue by Slavery89** [DEgITx/rats-search#67]
После последнего обновления и полного пропатчивания базы постоянно вылезает вот эта ошибка, каждые 2-3 минуты..
![default](https://user-images.githubusercontent.com/45933319/50073640-57b87100-022d-11e9-903e-7df80907067f.png)

**Comment by DEgITx** [comment]
если она присутствует в rats.log, можете его прикрепить, а то в окне к сожалению самое важное обрезано )

**Comment by Slavery89** [comment]
[rats.log](https://github.com/DEgITx/rats-search/files/2685538/rats.log)
Вторая половина лога почти целиком состоит из этих ошибок)

**Comment by DEgITx** [comment]
подобное воникает если временно перенести базу и запустить с новой?

**Comment by Slavery89** [comment]
Перенес базу, два часа - ошибок не наблюдается..
