### ISSUE TITLE
Fails with uncaught exception when not connected to the Internet

### ISSUE THREAD

**Issue by probonopd** [DEgITx/rats-search#7]
Fails with uncaught exception when not connected to the Internet

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/02c7a40f000daba0e9ee28c50cc7a12028821b8f/database/rats-search/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/426

**Comment by DEgITx** [comment]
in future build must be ok, recheck than

**Comment by probonopd** [comment]
Thank you very much. Please let me know when it is available for download.
