### ISSUE TITLE
баг в версии v1.1.0

### ISSUE THREAD

**Issue by Ruslan567vg** [DEgITx/rats-search#71]
Windows 10 x64
баг в версии v1.1.0 https://i.ibb.co/Xbc32jP/image.jpg и поиск в локальной базе не работает зачем нужно было вообще выкладывать версию v1.1.0 ?  в Debian версия 1.1.0 не запускается 

а вот в версии v1.0.0 все работает как часы как на Win так и на linux

**Comment by DEgITx** [comment]
исправлен в портативке в 1.1.1, если под дебиан проблемы - в отдельный багтикет с описанием, этот закрываю
