### ISSUE TITLE
версия v1.0.0 Windows 10 x64 ошибка

### ISSUE THREAD

**Issue by Ruslan567vg** [DEgITx/rats-search#73]
Скришот ошибки https://i.ibb.co/LhRGYB3/image.jpg начала появлятся после выхода версии 1.1.1

возможно из за того что я удалил все фаилы из папки data за исключением database

**Comment by 1tuz** [comment]
У меня то же самое. После обновления с версии 0.28 на совершенно любую регулярно появляется ошибка. А при откате на 0.28 вылезает назойливое предложение обновиться. По идее, если очистить все данные и установить rats "на чистую", ошибка пропадет, но терять напарсенный петабайт данных не хочется.

**Comment by DEgITx** [comment]
На 1.1.4 вылезать не должна, если будет переоткроете

**Comment by 1tuz** [comment]
Немного ошибся с топиком насчет ошибки. У меня немного другая: yadi.sk/i/EFYL_Prhx9wyhA . Возможно требуется предоставить какие-либо логи?

**Comment by DEgITx** [comment]
rats.log в папке в AppData\Roaming\Rats on The Boat

**Comment by 1tuz** [comment]
[rats.log](https://github.com/DEgITx/rats-search/files/2881335/rats.log)
