### ISSUE TITLE
Appimage not working in Manjaro

### ISSUE THREAD

**Issue by tiotrom** [DEgITx/rats-search#83]
Here's the error I get
```
[tio@tio-pc ~]$ '/home/tio/Applications/rats-search-1.1.4-i386_885ac1e2f6ac37a59d7aa6ae096fd7d2.AppImage' 
qt5ct: using qt5ct plugin
/tmp/.mount_rats-sZoxQto/rats-search: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

```

**Comment by DEgITx** [comment]
Try to install gtk3 package and run after

**Comment by tiotrom** [comment]
Already installed
![2019-03-14_15-15](https://user-images.githubusercontent.com/34804533/54363816-fbb68a80-466b-11e9-9ea5-ca30f57ad754.png)

**Comment by DEgITx** [comment]
Can you check than that "libgtk-3.so.0" file exist somewhere in system in /usr/lib directory? If not than try to install package where it's contains: something like libgtk-3 .

**Comment by tiotrom** [comment]
> Can you check than that "libgtk-3.so.0" file exist somewhere in system in /usr/lib directory?

Yes it is there
![2019-03-17_20-25](https://user-images.githubusercontent.com/34804533/54496698-d1c2c980-48f2-11e9-9a4a-0568a5e45ea6.png)

**Comment by tiotrom** [comment]
Ah this is embarassing I think I was trying the rats-search-1.1.4-i386.AppImage instead of rats-search-1.1.4-x86_64.AppImage - I apologize. The rats-search-1.1.4-x86_64.AppImage works! Also, I would love to see this in AUR :) - Cheers!

**Comment by DEgITx** [comment]
yes, I wanna mark this :)
