### ISSUE TITLE
Using nginx's proxy_pass to access via domain name will display a blank page

### ISSUE THREAD

**Issue by monkey000** [DEgITx/rats-search#89]
Using nginx's proxy_pass to access via domain name will display a blank page.
But through the ip: port access can display the normal page.
I don't know why there is such a problem. Can anyone provide me some help?

This is my nginx config:
```
server {
    listen 80;
    server_name docs.biubiubiu.dev;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443;
    server_name docs.biubiubiu.dev;
    ssl on;
    ssl_certificate  /etc/nginx/cert/1_docs.biubiubiu.dev_bundle.crt;
    ssl_certificate_key /etc/nginx/cert/2_docs.biubiubiu.dev.key;
    ssl_session_timeout 10m;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    proxy_set_header X-Forwarded-For $remote_addr;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
    server_tokens off;

    location / {
        proxy_pass         http://127.0.0.1:8095;
        proxy_redirect off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_set_header   X-Forwarded-Proto https;

        access_log      /var/log/nginx/seahub.access.log;
        error_log       /var/log/nginx/seahub.error.log;

        proxy_read_timeout  50000s;

        client_max_body_size 0;
    }


}
```

**Comment by DEgITx** [comment]
`    
     server {
        listen 8080;

	location / {
    	    proxy_pass         http://127.0.0.1:8095;
    	    proxy_redirect off;
    	    proxy_set_header   Host $host;
    	    proxy_set_header   X-Real-IP $remote_addr;
    	    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    	    proxy_set_header   X-Forwarded-Host $server_name;
    	    proxy_set_header   X-Forwarded-Proto https;

    	    proxy_read_timeout  50000s;

    	    client_max_body_size 0;
	}
    }
`
I tried the basic configuration without ssl and it works for me

**Comment by zella** [comment]
Same problem. I try run it in container with open vpn https://github.com/dperson/openvpn-client  To access I need use proxy. `-w "http://rats:8095/;/ratsearch` So I should able to access application on `http://localhost/ratsearch` And it's not working, I see white screen  and in browser console "http://localhost/app.js" 404
