### ISSUE TITLE
[gui] Warning

### ISSUE THREAD

**Issue by SparkYDevtk** [DEgITx/rats-search#99]
Доброе время суток. Поставил на своём сервере под управлением Ubuntu 18.04 вчера.
Все было хорошо. 
Начал наблюдать вот такое предупреждение.
[gui] Warning: Material-UI: The white color was not parsed correctly,
  because it has an unsupported format (color name or RGB %). This may cause issues in component rendering.

**Comment by SparkYDevtk** [comment]
При дропе торент файла вылетает ошибка и сервер останавливается. Я не нашел требований по версиям npm,  node
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'server' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle rats-search@1.3.0~preserver: rats-search@1.3.0
6 silly lifecycle rats-search@1.3.0~preserver: no script for preserver, continuing
7 info lifecycle rats-search@1.3.0~server: rats-search@1.3.0
8 verbose lifecycle rats-search@1.3.0~server: unsafe-perm in lifecycle true
9 verbose lifecycle rats-search@1.3.0~server: PATH: /usr/share/npm/bin/node-gyp-bin:/media/sparky/Store/rats-search-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle rats-search@1.3.0~server: CWD: /media/sparky/Store/rats-search-master
11 silly lifecycle rats-search@1.3.0~server: Args: [ '-c', 'node src/background/server.js' ]
12 silly lifecycle rats-search@1.3.0~server: Returned: code: 1  signal: null
13 info lifecycle rats-search@1.3.0~server: Failed to exec server script
14 verbose stack Error: rats-search@1.3.0 server: `node src/background/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid rats-search@1.3.0
16 verbose cwd /media/sparky/Store/rats-search-master
17 error Linux 4.15.0-58-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error rats-search@1.3.0 server: `node src/background/server.js`
22 error Exit status 1
23 error Failed at the rats-search@1.3.0 server script 'node src/background/server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the rats-search package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node src/background/server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs rats-search
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls rats-search
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SparkYDevtk** [comment]
Ошибка при дропе поменялась. Но результат тот же (ставил самую свежую версию)
Ubuntu 18.04 Bionic
[drop] drop torrents and replicate from original torrent files
/media/sparky/Store/rats-search/src/background/directoryFilesRecursive.js:9
			throw err
			^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at Object.readdirSync (fs.js:785:3)
    at directoryFilesRecursive (/media/sparky/Store/rats-search/src/background/directoryFilesRecursive.js:6:14)
    at _.flatten.pathTorrents.map.path (/media/sparky/Store/rats-search/src/background/spider.js:794:56)
    at Array.map (<anonymous>)
    at Socket.initialized.recive (/media/sparky/Store/rats-search/src/background/spider.js:794:44)
    at Socket.emit (events.js:198:13)
    at /media/sparky/Store/rats-search/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rats-search@1.3.0 server: `node src/background/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rats-search@1.3.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by DEgITx** [comment]
исправлено в мастер ветке
